### ISSUE TITLE
Wrong email send counts after upgrade from 0.7.1 to 1.0

### ISSUE THREAD

**Issue by davidkarban** [nitmir/policyd-rate-limit#13]
Hi, 

I have upgraded several days ago from Debian's version 0.7.1 to 1.0 thru pip. After the upgrade policyd started to count sent emails somewhat strange.

As an example, let`s say foo@bar.baz send only  7 emails sent in 24 hour period according to log, but it had more than 300 hits in the mail_count table. After I truncated the table and watched a little over it, some new emails that has entered there have increments in more than 10 per 1 email sent.

I have dug deeper, with debug and there was indeed increment on the address even when it was sent, from other address (emails changed to protect privacy):

```
waiting for connections
connection from b''
request=smtpd_access_policy
protocol_state=RCPT
protocol_name=ESMTP
client_address=217.16.190.69
client_name=www1.gzk.cz
client_port=49994
reverse_client_name=www1.domain.tld
helo_name=www1.domain.tld
sender=apache@www1.domain.tld
recipient=test@foo.bar
recipient_count=0
queue_id=
instance=2792.5dde5805.eb019.0
size=1906
etrn_domain=
stress=
sasl_method=
sasl_username=
sasl_sender=
ccert_subject=
ccert_issuer=
ccert_fingerprint=
ccert_pubkey_fingerprint=
encryption_protocol=
encryption_cipher=
encryption_keysize=0
policy_context=

000/250 hit since 86400s
insert id apache@www1.domain.tld

request=smtpd_access_policy
protocol_state=RCPT
protocol_name=ESMTP
client_address=181.41.216.145
client_name=unknown
client_port=40412
reverse_client_name=unknown
helo_name=[181.41.216.131]
sender=ps2c3hhkbqqyy@mti.com.ua
recipient=anothertest@fooooo.baz
recipient_count=0
queue_id=8184727032B
instance=2799.5dde5800.ccbe6.0
size=0
etrn_domain=
stress=
sasl_method=
sasl_username=
sasl_sender=
ccert_subject=
ccert_issuer=
ccert_fingerprint=
ccert_pubkey_fingerprint=
encryption_protocol=
encryption_cipher=
encryption_keysize=0
policy_context=

001/250 hit since 86400s
insert id apache@www1.domain.tld
action=dunno
```

I am using sasl or sender, this was without sasl auth. Two different senders, the first one has properly created the entry, but the second sender has been logged as the first one for some reason.

As I dug deeper, I have looked onto the differences between 0.7.1 - 1.0 and realized the socket reuse was added there. So I have checkouted the '7a173d39689848b56bca6b411600186805c17b31' commit and have build version of policyd before that change. Now it works well.

I will gladly (but somehow slowly, my schedule is tight)  help with solving this issue, if you need some test, debug logs or so, it is possible to get them.

**Comment by P-EB** [comment]
As I authored the changes in question I'll try to give it a look at some time. Thanks for the feedback and sorry for the inconvenience.

**Comment by P-EB** [comment]
@davidkarban sorry for not reacting earlier, can you try with the latest commit on master? I think it fixes the issue.
