### ISSUE TITLE
Rate limit is # of recipients, not # of messages

### ISSUE THREAD

**Issue by jeredfloyd** [nitmir/policyd-rate-limit#14]
With the default configuration of policyd check in smtpd_relay_restrictions, an entry is generated for each RCPT TO command.  This means that, with the default configuration, a single email with 11 recipients will be blocked.

It seems more likely that an administrator wishes to limit the number of message transactions.  This could be done by moving the policyd check to smtpd_data_restrictions (among other places), however policyd.py:225 limits actions to only RCPT phase.

I recommend this phase check be removed, and the documentation be updated to indicate configurations that limit number of recipients vs number of emails.

**Comment by kolorafa** [comment]
Personally i think it should count number of recipients (so it's working correct) - as it send separate email to every recipient, but ability to do both is fine by me :)

**Comment by jeredfloyd** [comment]
Perhaps both are desirable metrics? I already have smtpd_recipient_limit so that's why # of messages was more interesting.

I'll submit a patch when I have the spare time to do so.  (This could be a while, but at least I have a reminder set now.)

**Comment by P-EB** [comment]
@jeredfloyd this is a fair point. I am working on other projects, but if @nitmir has some time maybe we could design a configuration parameter that allows to decide the metrics.

**Comment by nitmir** [comment]
Hi @jeredfloyd 

Are you still interested to limit by number of submitted mail ? 

If so, I could create a new value for the option `count_mode`  and set it to `2` to do so

Cheers

**Comment by jeredfloyd** [comment]
Hi @nitmir !

I apologize that I never submitted a patch.  I ended up just commenting out the two lines that require 'protocol_state' to be 'RCPT', and then integrating into "smtpd_data_restrictions" rather than "smtpd_recipient_restrictions".  That had the desired result for me.

I see that you've done something similar in your new 1.1.0 release!  Since integrating with the DATA phase is now the recommended integration, I would appreciate adding the separate count_mode since my old hack will not work.

**Comment by nitmir** [comment]
#89fc699b289f3bdc7cce3bebd8ee0aa8d87b8785 should do the tricks
