### ISSUE TITLE
limits_by_id wont work for Postfix 3.1.15

### ISSUE THREAD

**Issue by macsurf** [nitmir/policyd-rate-limit#17]
Hello

I noticed that limits_by_id dont work with Postfix 3.1.15. My example config:

```
limits_by_id:
    www-data@example.com:
       - [1, 60]
```

logs:
```
in "/etc/policyd-rate-limit.yaml", line 63, column 1
in "/etc/policyd-rate-limit.yaml", line 58, column 1
```

Limits by IP client is also doesnt work.
  
```
limits_by_id:
     192.168.1.10:
            - [1, 60]
```

**Comment by nitmir** [comment]
Hi

The logs show a syntax error in the yaml configuration file.

You can use `python3 -c 'import yaml, sys; print(yaml.safe_load(sys.stdin))' < /etc/policyd-rate-limit.yaml` to validate your yaml and possibly to have a more verbose error message.

Cheers
