### ISSUE TITLE
policyd-rate-limit: error: unrecognized arguments: /usr/local/bin/policyd-rate-limit

### ISSUE THREAD

**Issue by Danrancan** [nitmir/policyd-rate-limit#19]
I'm running Ubuntu Server 20.04 with postfix/dovecot.

When running `sudo policyd-rate-limit /usr/local/bin/policyd-rate-limit --clean >/dev/null` in crontab or directly from the terminal, i get the error "policyd-rate-limit: error: unrecognized arguments: /usr/local/bin/policyd-rate-limit". Could someone help me debug this?

**Comment by Danrancan** [comment]
It seems that the command 
```
sudo policyd-rate-limit --file /etc/policyd-rate-limit.yaml --clean
```
actually deletes old records on ubuntu. So the corresponding root crontab command would be this:
```
0 0 * * * policyd-rate-limit --file /etc/policyd-rate-limit.yaml --clean
```
This should be changed in the README File.

**Comment by nitmir** [comment]
Hi

The README specify to run `policyd-rate-limit --clean` on a regular basis and also explain the usage of `--file`. It does not have the ambition to explain how to use cron or to specify the crontab format. You could also use a systemd timer.

The example given is correct for the global system crontab (file `/etc/crontab`) if the README installation procedure was used.

Cheers
