### ISSUE TITLE
limits in mysql-db too

### ISSUE THREAD

**Issue by HansMeiser234** [nitmir/policyd-rate-limit#2]
Hello,

this service seems to be good work, i will try to use it.
have one question: it is planned to have limits etc. stored in mysql-db too? this would be much easier for automated limiting. otherweise i had to write a script which is editing the -yaml config and reloads the deamon. Would be nice if there would be a way that yaml-config contains only db-data.

Thanks,
Hajo

**Comment by nitmir** [comment]
That was not originally intended to, but there already everything for db communication so why not. Personally, I only use static limits, that's why it's in the yaml config, I'll try to look at it when I'll get some spare time.

**Comment by HansMeiser234** [comment]
Hello,

sorry for my late response, had the flu last weeks. thanks for thinking about it. we had some spamproblems with new fake users.  we want to limit them first days. setting limits/removing restrictions in mysql is much easier and more comfy then editing a text-conf by script. also limits could be read live without reloading a service after every change.

Thanks,
Hajo

**Comment by dfateyev** [comment]
It's a pity if it's not yet implemented. Message limits can be dynamic, so there is no point to retrieve and adjust them in config files, using database is much more usable.

**Comment by nitmir** [comment]
Is someone willing to submit a Pull request for this feature and the corresponding unit tests ?

I am not planning to develop and test it myself

**Comment by nitmir** [comment]
Fixed by cf0e11ade61072bac32ed9e8eb4279d95e9e3a08
