### ISSUE TITLE
impossible to work with mysql

### ISSUE THREAD

**Issue by TBAIKamine** [nitmir/policyd-rate-limit#22]
thank you for your contribution to the open source community but this program just can't work with mysql.
your readme has impossible senarios:

- [mysqldb](https://pypi.python.org/pypi/MySQL-python) sudo apt-get install python3-mysqldb

first of all that hyperlink takes to this page https://pypi.org/project/MySQL-python where it says: "_Python-2.4 through 2.7 are currently supported_"
however you're suggesting not to install it via pip but to install it via a linux package called "python3-mysqldb" (for debian like distros)
per debian package info [here](https://packages.debian.org/bullseye/python3-mysqldb) that package is compatible with python >= 3.9~ to << 3.10
I have an ubuntu, per ubuntu package page [here](https://packages.ubuntu.com/focal/python3-mysqldb) that package is compatible with python >= 3.8~ to << 3.9
I tried every python version in pyenv, every possible ubuntu and pip package. it's either an error with the build or policyd-rate-limit just doesn't do anything with the mysql database.
could you please update your readme with what environement details you tested your code in ?
what's puzzling me is your [utils.py](https://github.com/nitmir/policyd-rate-limit/blob/master/policyd_rate_limit/utils.py) line 219 has "_import MySQLdb_", so the linux packages won't work with that line because they have different names.
maybe it would be better to check what python mysql package is installed then use an _import as_ ?

**Comment by nitmir** [comment]
I've updated the readme to point the the maintained version of mysqldb (a fork of the old link).

I don't understand clearly what's your other issues or why you are talking about « python compatibility ». On a specific distro, python-mysqldb is compiled for the python version packaged with this distro and thus compatible with the python version of that distro.

Installing python3-mysqldb install a python module named `MySQLdb`.

Using pyenv is not a supported method of installation. If you'll care to document it, you're wellcome.

BTW policyd-rate-limit is packaged in ubuntu (https://packages.ubuntu.com/focal/policyd-rate-limit) so unless you're searching for a newver version, you should just do ` apt install policyd-rate-limit`.

Cheers
