### ISSUE TITLE
Use sender as ID

### ISSUE THREAD

**Issue by smsoft-ru** [nitmir/policyd-rate-limit#3]
In case of webmail as frontend to SMTP server, SASL authentication not used, and IP address always is the same. I suggest to use sender e-mail address as ID in this (and many other) case. I created patch to add this functionality (see attachment). Sender address is used if SASL ID not found or disabled. IP address as ID is used on third place, as last resort.

Some other suggestions:
 - Exclusions from rate-limited IP addressess list. For example, it is difficult to create IP addressess list which includes all besides localhost (127.0.0.0/8).
 - Ability to reorder criteria to use SASL ID, sender or IP address as ID.

[policyd-rate-limit-master.zip](https://github.com/nitmir/policyd-rate-limit/files/691027/policyd-rate-limit-master.zip)

**Comment by nitmir** [comment]
Hi, I have added your patch. However, I suspect it will also limit the number of mails you receive from the internet (incoming emails) by sender. I do not known if you want that or not. I think it can be interesting although it was not in the original spirit of the daemon which was to limit outgoing emails.

Maybe limiting only senders from specific domain could be useful (ie, limit only for my users). Moreover, as anyone can spoof anyone emails, to avoid someone on the internet to DoS one of your users (send mails as one of your user to your server to trigger the sender limit and prevent this user to send mails), I think it could also be usefull to allow to only count by sender if the mail comes from a trusted ip.

**Comment by nitmir** [comment]
Currently I do not really see the point of reordering criterias (SASL ID, sender or IP address as ID). Indeed, the IP address and sender address are always present. So:
* order [ip, sender, sasl] and [ip, sasl; sender] are equivalent to limit_by_ip: True, limit_by_sender: False, limit_by_sasl: False
* order [sender, ip, sasl] and [sender, sasl, ip] are equivalent to limit_by_sender: True, limit_by_ip: False, limit_by_sasl: False
* order [sasl, ip, sender] is equivalent to limit_by_sender: False, limit_by_ip: True, limit_by_sasl: True
* order [sasl, sender, ip] is equivalent to limit_by_sender: True, limit_by_ip: False, limit_by_sasl: True

This could however be useful if limit by sender is not apply to all emails by only to certain domains or ip addresses.

**Comment by smsoft-ru** [comment]
The primary goal of my patch was to protect corporate mail server from became open relay. Remote users of corporate mail server are able to send outgoing mail via SMTP, IMAP or Webmail (all this with SSL) afrer SASL authentication. But if some user have weak stealed or brute-forced password, this scheme may become open relay. Using this patch I can limit outgoing mail (which came from outside via IMAP due to leaked password) and can quickly block this user. Limiting occur by e-mail, which in turn corresponds with IMAP/SMTP/Webmail login.

Yes, reordering have sense if limits can be applied with exclusions. I suggest to add include/exclude regexps for SASL and e-mail. Also these regexps can eliminate side effect mentioneed by you - limiting incoming mail.

**Comment by nitmir** [comment]
Hi,

I'll close this issue as the initial use case is fixed.

Is someone is still interested by adding support for include/exclude regexps for sasl and sender please open a new issue (and maybe a pull request).
