### ISSUE TITLE
'86400s' must not be longer than 5

### ISSUE THREAD

**Issue by joesanta555** [nitmir/policyd-rate-limit#5]
When I call /usr/bin/policyd-rate-limit --clean, I get this:

32 records deleted
'86400s' must not be longer than 5

the return value is 8

My configuration...
limits:
    - [35, 120] 
    - [1000, 86400] 

What is wrong? Also the notification emails are not working but I think it is due to the fact that the scripts ends before sending the report

thank you

**Comment by nitmir** [comment]
Hi

This is normally fixed in 73fb7fc7182b95150c4e67bb64acd3e16601cb0d
