### ISSUE TITLE
int object is not iterable

### ISSUE THREAD

**Issue by truhlik** [nitmir/policyd-rate-limit#7]
Hi guys,

running this daemon with attached configuration produce error mentioned in subject.
Have any idea why?

If I set `limit_by_ip: False` then there is no error, but then I am still getting "dunno" for each mail.

[policyd-rate-limit.txt](https://github.com/nitmir/policyd-rate-limit/files/1376976/policyd-rate-limit.txt)

**Comment by nitmir** [comment]
Hi,
```limits:``` is suppose to be a list of tuple (a list of list) and yours is just a list of 2 interger.
You should change:
```limits: [2, 500]```
to
```limits: [[2, 500]]```
or the equivalent and recommended notation
```
limits:
    - [2, 500]
```

**Comment by truhlik** [comment]
Thank you, for the answer. It fixed the problem.
I am currently able to limit senders by ip, but limit by username or sasl is not working. 
Seems for me that information about username/sasl is not passed from postfix to policyd.

> waiting for connections
> connection from b''
> request=smtpd_access_policy
> protocol_state=RCPT
> protocol_name=ESMTP
> client_address=::1
> client_name=localhost
> client_port=46866
> reverse_client_name=localhost
> helo_name=email.itporadce.cz
> sender=postmaster@it-poradce.cz
> recipient=lubos@it-poradce.cz
> recipient_count=0
> queue_id=
> instance=75c.59df7ea1.56819.0
> size=0
> etrn_domain=
> stress=
> sasl_method=
> sasl_username=
> sasl_sender=
> ccert_subject=
> ccert_issuer=
> ccert_fingerprint=
> ccert_pubkey_fingerprint=
> encryption_protocol=
> encryption_cipher=
> encryption_keysize=0
> policy_context=

**Comment by nitmir** [comment]
Are you sure that your are using authentication then sending the email ?
[The postfix documentation clearly state](http://www.postfix.org/SMTPD_POLICY_README.html):
« The "sasl_*" attributes (Postfix 2.2 and later) specify information about how the client was authenticated via SASL. These attributes are empty in case of no SASL authentication. »

**Comment by truhlik** [comment]
No, I am not sure :-) And after looking to the log file i think that there is no SASL.
Seems that using webmail SASL is not used for postfix. Is there any option, how to limit these users?
Thx very much.

> Oct 13 12:31:51 email postfix/smtpd[17132]: E4DD6101544: client=localhost[127.0.0.1]
Oct 13 12:31:52 email postfix/cleanup[17120]: E4DD6101544: message-id=<kcim.59e09613.42d9.3c02d73c05eb066f@email.itporadce.cz>
Oct 13 12:31:52 email postfix/qmgr[16570]: E4DD6101544: from=<lubos@it-poradce.cz>, size=2159, nrcpt=1 (queue active)
Oct 13 12:31:52 email clamsmtpd: 1002FF: from=lubos@it-poradce.cz, to=lubos@it-poradce.cz, status=CLEAN
Oct 13 12:31:52 email postfix/smtp[17130]: AD6B81015FC: to=<lubos@it-poradce.cz>, relay=127.0.0.1[127.0.0.1]:10025, delay=0.69, delays=0.14/0.05/0.1/0.39, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as E4DD6101544)
Oct 13 12:31:52 email postfix/smtpd[17132]: disconnect from localhost[127.0.0.1] ehlo=1 xforward=1 mail=1 rcpt=1 data=1 quit=1 commands=6
Oct 13 12:31:53 email postfix/qmgr[16570]: AD6B81015FC: removed
Oct 13 12:31:54 email spamd[999]: prefork: child states: II
Oct 13 12:31:54 email postfix/lmtp[17134]: E4DD6101544: to=<lubos@it-poradce.cz>, relay=127.0.0.1[127.0.0.1]:2003, delay=3.5, delays=0.37/0.13/0.33/2.7, dsn=2.1.5, status=sent (250 2.1.5 lubos@it-poradce.cz Ok)
Oct 13 12:31:54 email postfix/qmgr[16570]: E4DD6101544: removed

**Comment by nitmir** [comment]
You should configure submission with authentication on postfix and tell your webmail to authenticate to send mails.

« Port 587 is submission, for user submission of mail, NOT suitable for mail exchange. See the commented example in master.cf »

Somethings like:

    submission      inet n       -       -       -       -       smtpd
      -o smtpd_tls_security_level=encrypt
      -o smtpd_sasl_auth_enable=yes
      -o smtpd_tls_session_cache_database=btree:${data_directory}/smtpd_scache
      -o smtpd_client_restrictions=permit_sasl_authenticated,reject

And of course, you need to configure sasl on postfix in main.cf. The way to do it will mostly depend on your user backend.

Here an example of how to do it with dovecot https://wiki2.dovecot.org/HowTo/PostfixAndDovecotSASL
