### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by sumpfralle** [nitmir/policyd-rate-limit#9]
This would be nice (e.g. for the Debian package maintainer) in order to have a fix for #5 included.

Thank you for your time!

**Comment by nitmir** [comment]
Yes, it would be nice, sadly, I am also the Debian package maintainer and I have currently almost no time for this project.
I'll try to make a release this weekend, but I wont probably have time to package it to the Debian archive.

**Comment by P-EB** [comment]
I can take care of it.

@nitmir poke me if you wish.
